package com.gooddoctor.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOXED_MEDICINE.
 */
public class BoxedMedicine {

    private Long id;
    private String medicineId;
    private String medicineName;
    private String companyName;

    public BoxedMedicine() {
    }

    public BoxedMedicine(Long id) {
        this.id = id;
    }

    public BoxedMedicine(Long id, String medicineId, String medicineName, String companyName) {
        this.id = id;
        this.medicineId = medicineId;
        this.medicineName = medicineName;
        this.companyName = companyName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

}
