package com.gooddoctor.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gooddoctor.data.dao.Disease;
import com.gooddoctor.data.dao.BoxedMedicine;
import com.gooddoctor.data.dao.MedicineBox;
import com.gooddoctor.data.dao.Notification;

import com.gooddoctor.data.dao.DiseaseDao;
import com.gooddoctor.data.dao.BoxedMedicineDao;
import com.gooddoctor.data.dao.MedicineBoxDao;
import com.gooddoctor.data.dao.NotificationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diseaseDaoConfig;
    private final DaoConfig boxedMedicineDaoConfig;
    private final DaoConfig medicineBoxDaoConfig;
    private final DaoConfig notificationDaoConfig;

    private final DiseaseDao diseaseDao;
    private final BoxedMedicineDao boxedMedicineDao;
    private final MedicineBoxDao medicineBoxDao;
    private final NotificationDao notificationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diseaseDaoConfig = daoConfigMap.get(DiseaseDao.class).clone();
        diseaseDaoConfig.initIdentityScope(type);

        boxedMedicineDaoConfig = daoConfigMap.get(BoxedMedicineDao.class).clone();
        boxedMedicineDaoConfig.initIdentityScope(type);

        medicineBoxDaoConfig = daoConfigMap.get(MedicineBoxDao.class).clone();
        medicineBoxDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        diseaseDao = new DiseaseDao(diseaseDaoConfig, this);
        boxedMedicineDao = new BoxedMedicineDao(boxedMedicineDaoConfig, this);
        medicineBoxDao = new MedicineBoxDao(medicineBoxDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);

        registerDao(Disease.class, diseaseDao);
        registerDao(BoxedMedicine.class, boxedMedicineDao);
        registerDao(MedicineBox.class, medicineBoxDao);
        registerDao(Notification.class, notificationDao);
    }
    
    public void clear() {
        diseaseDaoConfig.getIdentityScope().clear();
        boxedMedicineDaoConfig.getIdentityScope().clear();
        medicineBoxDaoConfig.getIdentityScope().clear();
        notificationDaoConfig.getIdentityScope().clear();
    }

    public DiseaseDao getDiseaseDao() {
        return diseaseDao;
    }

    public BoxedMedicineDao getBoxedMedicineDao() {
        return boxedMedicineDao;
    }

    public MedicineBoxDao getMedicineBoxDao() {
        return medicineBoxDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

}
