package com.gooddoctor.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gooddoctor.data.Disease;
import com.gooddoctor.data.Medicine;

import com.gooddoctor.data.DiseaseDao;
import com.gooddoctor.data.MedicineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diseaseDaoConfig;
    private final DaoConfig medicineDaoConfig;

    private final DiseaseDao diseaseDao;
    private final MedicineDao medicineDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diseaseDaoConfig = daoConfigMap.get(DiseaseDao.class).clone();
        diseaseDaoConfig.initIdentityScope(type);

        medicineDaoConfig = daoConfigMap.get(MedicineDao.class).clone();
        medicineDaoConfig.initIdentityScope(type);

        diseaseDao = new DiseaseDao(diseaseDaoConfig, this);
        medicineDao = new MedicineDao(medicineDaoConfig, this);

        registerDao(Disease.class, diseaseDao);
        registerDao(Medicine.class, medicineDao);
    }
    
    public void clear() {
        diseaseDaoConfig.getIdentityScope().clear();
        medicineDaoConfig.getIdentityScope().clear();
    }

    public DiseaseDao getDiseaseDao() {
        return diseaseDao;
    }

    public MedicineDao getMedicineDao() {
        return medicineDao;
    }

}
