package com.gooddoctor.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table MEDICINE.
 */
public class Medicine {

    private Long id;
    private String medicineId;
    private String name;
    private String commonName;
    private String efficacy;
    private String imageUrl;
    private String companyName;
    private String price;
    private Integer type;
    private Integer attribute;

    public Medicine() {
    }

    public Medicine(Long id) {
        this.id = id;
    }

    public Medicine(Long id, String medicineId, String name, String commonName, String efficacy, String imageUrl, String companyName, String price, Integer type, Integer attribute) {
        this.id = id;
        this.medicineId = medicineId;
        this.name = name;
        this.commonName = commonName;
        this.efficacy = efficacy;
        this.imageUrl = imageUrl;
        this.companyName = companyName;
        this.price = price;
        this.type = type;
        this.attribute = attribute;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getEfficacy() {
        return efficacy;
    }

    public void setEfficacy(String efficacy) {
        this.efficacy = efficacy;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getAttribute() {
        return attribute;
    }

    public void setAttribute(Integer attribute) {
        this.attribute = attribute;
    }
}
