package com.xywy.drug.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xywy.drug.data.dao.DBBoxedMedicine;
import com.xywy.drug.data.dao.DBMedicineBox;
import com.xywy.drug.data.dao.DBNotification;
import com.xywy.drug.data.dao.DBSearchHistory;

import com.xywy.drug.data.dao.DBBoxedMedicineDao;
import com.xywy.drug.data.dao.DBMedicineBoxDao;
import com.xywy.drug.data.dao.DBNotificationDao;
import com.xywy.drug.data.dao.DBSearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBBoxedMedicineDaoConfig;
    private final DaoConfig dBMedicineBoxDaoConfig;
    private final DaoConfig dBNotificationDaoConfig;
    private final DaoConfig dBSearchHistoryDaoConfig;

    private final DBBoxedMedicineDao dBBoxedMedicineDao;
    private final DBMedicineBoxDao dBMedicineBoxDao;
    private final DBNotificationDao dBNotificationDao;
    private final DBSearchHistoryDao dBSearchHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBBoxedMedicineDaoConfig = daoConfigMap.get(DBBoxedMedicineDao.class).clone();
        dBBoxedMedicineDaoConfig.initIdentityScope(type);

        dBMedicineBoxDaoConfig = daoConfigMap.get(DBMedicineBoxDao.class).clone();
        dBMedicineBoxDaoConfig.initIdentityScope(type);

        dBNotificationDaoConfig = daoConfigMap.get(DBNotificationDao.class).clone();
        dBNotificationDaoConfig.initIdentityScope(type);

        dBSearchHistoryDaoConfig = daoConfigMap.get(DBSearchHistoryDao.class).clone();
        dBSearchHistoryDaoConfig.initIdentityScope(type);

        dBBoxedMedicineDao = new DBBoxedMedicineDao(dBBoxedMedicineDaoConfig, this);
        dBMedicineBoxDao = new DBMedicineBoxDao(dBMedicineBoxDaoConfig, this);
        dBNotificationDao = new DBNotificationDao(dBNotificationDaoConfig, this);
        dBSearchHistoryDao = new DBSearchHistoryDao(dBSearchHistoryDaoConfig, this);

        registerDao(DBBoxedMedicine.class, dBBoxedMedicineDao);
        registerDao(DBMedicineBox.class, dBMedicineBoxDao);
        registerDao(DBNotification.class, dBNotificationDao);
        registerDao(DBSearchHistory.class, dBSearchHistoryDao);
    }
    
    public void clear() {
        dBBoxedMedicineDaoConfig.getIdentityScope().clear();
        dBMedicineBoxDaoConfig.getIdentityScope().clear();
        dBNotificationDaoConfig.getIdentityScope().clear();
        dBSearchHistoryDaoConfig.getIdentityScope().clear();
    }

    public DBBoxedMedicineDao getDBBoxedMedicineDao() {
        return dBBoxedMedicineDao;
    }

    public DBMedicineBoxDao getDBMedicineBoxDao() {
        return dBMedicineBoxDao;
    }

    public DBNotificationDao getDBNotificationDao() {
        return dBNotificationDao;
    }

    public DBSearchHistoryDao getDBSearchHistoryDao() {
        return dBSearchHistoryDao;
    }

}
