package com.xywy.drug.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBMEDICINE_BOX.
 */
public class DBMedicineBox {

    private Long id;
    private String personName;
    private String personImage;
    private Integer personGender;
    private Integer personAge;
    private String medicines;

    public DBMedicineBox() {
    }

    public DBMedicineBox(Long id) {
        this.id = id;
    }

    public DBMedicineBox(Long id, String personName, String personImage, Integer personGender, Integer personAge, String medicines) {
        this.id = id;
        this.personName = personName;
        this.personImage = personImage;
        this.personGender = personGender;
        this.personAge = personAge;
        this.medicines = medicines;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getPersonImage() {
        return personImage;
    }

    public void setPersonImage(String personImage) {
        this.personImage = personImage;
    }

    public Integer getPersonGender() {
        return personGender;
    }

    public void setPersonGender(Integer personGender) {
        this.personGender = personGender;
    }

    public Integer getPersonAge() {
        return personAge;
    }

    public void setPersonAge(Integer personAge) {
        this.personAge = personAge;
    }

    public String getMedicines() {
        return medicines;
    }

    public void setMedicines(String medicines) {
        this.medicines = medicines;
    }

}
