package com.xywy.drug.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBMEDICINE_BOX.
 */
public class DBMedicineBox {

    private Long id;
    private String name;
    private String medicineIds;
    private String syncId;
    private String owner;

    public DBMedicineBox() {
    }

    public DBMedicineBox(Long id) {
        this.id = id;
    }

    public DBMedicineBox(Long id, String name, String medicineIds, String syncId, String owner) {
        this.id = id;
        this.name = name;
        this.medicineIds = medicineIds;
        this.syncId = syncId;
        this.owner = owner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMedicineIds() {
        return medicineIds;
    }

    public void setMedicineIds(String medicineIds) {
        this.medicineIds = medicineIds;
    }

    public String getSyncId() {
        return syncId;
    }

    public void setSyncId(String syncId) {
        this.syncId = syncId;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

}
