package com.xywy.drug.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBNOTIFICATION.
 */
public class DBNotification {

    private Long id;
    private String medicineId;
    private String medicineName;
    private Integer duration;
    private Integer repeatPerDay;
    private String timePoints;
    private String syncId;
    private String owner;
    private Boolean notificationEnabled;

    public DBNotification() {
    }

    public DBNotification(Long id) {
        this.id = id;
    }

    public DBNotification(Long id, String medicineId, String medicineName, Integer duration, Integer repeatPerDay, String timePoints, String syncId, String owner, Boolean notificationEnabled) {
        this.id = id;
        this.medicineId = medicineId;
        this.medicineName = medicineName;
        this.duration = duration;
        this.repeatPerDay = repeatPerDay;
        this.timePoints = timePoints;
        this.syncId = syncId;
        this.owner = owner;
        this.notificationEnabled = notificationEnabled;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Integer getRepeatPerDay() {
        return repeatPerDay;
    }

    public void setRepeatPerDay(Integer repeatPerDay) {
        this.repeatPerDay = repeatPerDay;
    }

    public String getTimePoints() {
        return timePoints;
    }

    public void setTimePoints(String timePoints) {
        this.timePoints = timePoints;
    }

    public String getSyncId() {
        return syncId;
    }

    public void setSyncId(String syncId) {
        this.syncId = syncId;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Boolean getNotificationEnabled() {
        return notificationEnabled;
    }

    public void setNotificationEnabled(Boolean notificationEnabled) {
        this.notificationEnabled = notificationEnabled;
    }

}
