package com.xywy.drug.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBSEARCH_HISTORY.
 */
public class DBSearchHistory {

    private Long id;
    private String keyword;
    private Integer searchType;
    private String owner;
    private String syncId;

    public DBSearchHistory() {
    }

    public DBSearchHistory(Long id) {
        this.id = id;
    }

    public DBSearchHistory(Long id, String keyword, Integer searchType, String owner, String syncId) {
        this.id = id;
        this.keyword = keyword;
        this.searchType = searchType;
        this.owner = owner;
        this.syncId = syncId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Integer getSearchType() {
        return searchType;
    }

    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getSyncId() {
        return syncId;
    }

    public void setSyncId(String syncId) {
        this.syncId = syncId;
    }

}
